/* The following code was generated by JFlex 1.6.0 */

package lexico;
import static lexico.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>C:/Users/Luis/Documents/NetBeansProjects/Lexico/src/lexico/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\11\1\13\1\14\1\14\1\13\22\0\1\5\1\16\1\4"+
    "\1\0\1\10\1\0\1\32\1\0\1\34\1\35\1\20\1\17\1\63"+
    "\1\3\1\7\1\12\12\2\1\60\2\0\1\15\1\47\1\46\1\0"+
    "\1\44\1\6\1\42\1\55\4\6\1\56\2\6\1\43\5\6\1\57"+
    "\1\45\7\6\4\0\1\1\1\0\1\25\1\26\1\22\1\53\1\21"+
    "\1\54\1\6\1\23\1\50\1\6\1\41\1\37\1\61\1\40\1\24"+
    "\1\62\1\6\1\31\1\27\1\30\1\51\3\6\1\33\1\6\1\52"+
    "\1\36\10\0\1\14\u1fa2\0\1\14\1\14\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\2"+
    "\2\1\1\6\1\7\1\1\1\10\1\11\4\2\5\1"+
    "\1\2\1\1\1\12\1\2\1\13\1\14\1\0\1\15"+
    "\1\16\1\17\1\20\1\5\1\21\1\22\1\23\1\24"+
    "\10\2\1\25\2\2\1\26\1\27\5\0\1\30\1\31"+
    "\1\32\1\2\1\33\1\34\2\2\1\13\1\35\1\13"+
    "\1\17\15\2\5\0\4\2\1\36\1\37\6\2\1\40"+
    "\7\2\5\0\5\2\1\41\2\2\1\42\1\43\1\2"+
    "\1\44\1\2\1\45\1\46\1\2\1\47\1\50\5\0"+
    "\4\2\1\51\1\2\1\52\3\2\2\0\1\53\1\54"+
    "\1\0\3\2\1\55\5\2\1\56\1\0\1\57\1\60"+
    "\3\2\1\61\1\62\1\63\1\0\1\64\2\2\1\65"+
    "\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[176];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\64\0\u0138"+
    "\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\64\0\u02a4"+
    "\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444"+
    "\0\u0478\0\u04ac\0\64\0\u04e0\0\u0514\0\64\0\u0104\0\64"+
    "\0\64\0\u0548\0\64\0\u057c\0\64\0\64\0\64\0\64"+
    "\0\u05b0\0\u05e4\0\u0618\0\u064c\0\u0680\0\u06b4\0\u06e8\0\u071c"+
    "\0\u0138\0\u0750\0\u0784\0\64\0\64\0\u07b8\0\u07ec\0\u0820"+
    "\0\u0854\0\u0888\0\64\0\64\0\64\0\u08bc\0\u0138\0\64"+
    "\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0\0\u09f4\0\u0a28\0\u0a5c"+
    "\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\u0b60\0\u0b94\0\u0bc8\0\u0bfc"+
    "\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\u0d00\0\u0d34\0\u0d68\0\u0d9c"+
    "\0\u0dd0\0\u0e04\0\u0e38\0\u0e6c\0\u0138\0\u0ea0\0\u0ed4\0\u0f08"+
    "\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8\0\u0138\0\u100c\0\u1040\0\u1074"+
    "\0\u10a8\0\u10dc\0\u1110\0\u1144\0\u1178\0\u11ac\0\u11e0\0\u1214"+
    "\0\u1248\0\u127c\0\u12b0\0\u12e4\0\u1318\0\u134c\0\u0138\0\u1380"+
    "\0\u13b4\0\u0138\0\u0138\0\u13e8\0\u0138\0\u141c\0\u0138\0\u0138"+
    "\0\u1450\0\u0138\0\u0138\0\u1484\0\u14b8\0\u14ec\0\u1520\0\u1554"+
    "\0\u1588\0\u15bc\0\u15f0\0\u1624\0\u0138\0\u1658\0\u168c\0\u16c0"+
    "\0\u16f4\0\u1728\0\u175c\0\u1790\0\64\0\64\0\u17c4\0\u17f8"+
    "\0\u182c\0\u1860\0\u0138\0\u1894\0\u18c8\0\u18fc\0\u1930\0\u1964"+
    "\0\64\0\u1998\0\u0138\0\u0138\0\u19cc\0\u1a00\0\u1a34\0\u0138"+
    "\0\u0138\0\u0138\0\u1a68\0\u0138\0\u1a9c\0\u1ad0\0\u0138\0\u0138";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[176];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\7\1\13\1\7\1\0\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\2\10\1\22\1\23\3\10\1\24"+
    "\1\10\1\25\1\2\1\26\7\10\1\27\1\2\2\10"+
    "\1\30\1\31\4\10\1\32\2\10\1\33\65\0\1\34"+
    "\1\10\3\0\1\10\12\0\11\10\1\0\1\10\3\0"+
    "\7\10\2\0\2\10\1\0\5\10\1\0\2\10\3\0"+
    "\1\4\4\0\1\35\56\0\1\4\1\36\62\0\1\37"+
    "\1\0\1\40\2\37\12\0\11\37\1\0\1\37\3\0"+
    "\7\37\2\0\2\37\1\0\5\37\1\0\2\37\2\0"+
    "\2\10\3\0\1\10\12\0\11\10\1\0\1\10\3\0"+
    "\7\10\2\0\2\10\1\0\5\10\1\0\2\10\16\0"+
    "\1\41\47\0\1\42\4\0\1\42\12\0\11\42\1\0"+
    "\1\42\3\0\7\42\2\0\2\42\1\43\5\42\1\0"+
    "\2\42\13\0\1\44\2\0\1\45\63\0\1\46\31\0"+
    "\1\47\31\0\1\50\50\0\1\4\62\0\2\10\3\0"+
    "\1\10\12\0\1\10\1\51\7\10\1\0\1\10\3\0"+
    "\1\52\1\53\5\10\2\0\2\10\1\0\5\10\1\0"+
    "\1\54\1\10\2\0\2\10\3\0\1\10\12\0\3\10"+
    "\1\55\1\56\4\10\1\0\1\10\3\0\1\57\6\10"+
    "\2\0\2\10\1\0\5\10\1\0\2\10\2\0\2\10"+
    "\3\0\1\10\12\0\5\10\1\60\1\61\1\10\1\62"+
    "\1\0\1\10\3\0\7\10\2\0\2\10\1\0\5\10"+
    "\1\0\2\10\2\0\2\10\3\0\1\10\12\0\10\10"+
    "\1\63\1\0\1\10\3\0\7\10\2\0\2\10\1\0"+
    "\5\10\1\0\2\10\16\0\1\64\14\0\1\65\56\0"+
    "\1\66\1\67\2\0\1\70\21\0\1\71\1\72\45\0"+
    "\1\73\74\0\1\74\62\0\1\75\16\0\2\10\3\0"+
    "\1\10\12\0\1\76\2\10\1\77\5\10\1\0\1\10"+
    "\3\0\7\10\2\0\2\10\1\0\5\10\1\0\2\10"+
    "\61\0\1\100\4\0\2\10\3\0\1\10\12\0\11\10"+
    "\1\0\1\10\3\0\3\10\1\101\3\10\2\0\2\10"+
    "\1\0\2\10\1\102\2\10\1\0\2\10\2\0\1\103"+
    "\1\104\3\0\1\103\1\105\11\0\11\103\1\0\1\103"+
    "\3\0\7\103\2\0\2\103\1\0\5\103\1\0\2\103"+
    "\2\0\1\42\1\106\3\0\1\42\12\0\11\42\1\0"+
    "\1\42\3\0\7\42\2\0\2\42\1\0\5\42\1\0"+
    "\2\42\1\0\13\44\2\0\47\44\1\0\2\10\3\0"+
    "\1\10\12\0\2\10\1\107\6\10\1\0\1\10\3\0"+
    "\7\10\2\0\2\10\1\0\5\10\1\0\2\10\2\0"+
    "\2\10\3\0\1\10\12\0\6\10\1\110\2\10\1\0"+
    "\1\10\3\0\7\10\2\0\2\10\1\0\5\10\1\0"+
    "\2\10\2\0\2\10\3\0\1\10\12\0\11\10\1\0"+
    "\1\10\3\0\7\10\2\0\2\10\1\0\1\111\4\10"+
    "\1\0\2\10\2\0\2\10\3\0\1\10\12\0\11\10"+
    "\1\0\1\10\3\0\7\10\2\0\2\10\1\0\5\10"+
    "\1\0\1\10\1\112\2\0\2\10\3\0\1\10\12\0"+
    "\11\10\1\0\1\10\3\0\1\10\1\113\5\10\2\0"+
    "\2\10\1\0\5\10\1\0\2\10\2\0\2\10\3\0"+
    "\1\10\12\0\6\10\1\114\1\115\1\10\1\0\1\10"+
    "\3\0\1\116\6\10\2\0\2\10\1\0\5\10\1\0"+
    "\2\10\2\0\2\10\3\0\1\10\12\0\3\10\1\117"+
    "\1\120\4\10\1\0\1\10\3\0\7\10\2\0\2\10"+
    "\1\0\5\10\1\0\2\10\2\0\2\10\3\0\1\10"+
    "\12\0\6\10\1\121\2\10\1\0\1\10\3\0\7\10"+
    "\2\0\2\10\1\0\5\10\1\0\2\10\2\0\2\10"+
    "\3\0\1\10\12\0\10\10\1\122\1\0\1\10\3\0"+
    "\7\10\2\0\2\10\1\0\5\10\1\0\2\10\2\0"+
    "\2\10\3\0\1\10\12\0\1\123\10\10\1\0\1\10"+
    "\3\0\7\10\2\0\2\10\1\0\5\10\1\0\2\10"+
    "\32\0\1\124\56\0\1\125\60\0\1\126\66\0\1\127"+
    "\76\0\1\130\25\0\2\10\3\0\1\10\12\0\1\10"+
    "\1\131\7\10\1\0\1\10\3\0\7\10\2\0\2\10"+
    "\1\0\1\10\1\132\3\10\1\0\2\10\2\0\2\10"+
    "\3\0\1\10\12\0\11\10\1\0\1\10\3\0\4\10"+
    "\1\133\2\10\2\0\2\10\1\0\5\10\1\0\2\10"+
    "\2\0\2\10\3\0\1\10\12\0\11\10\1\0\1\10"+
    "\3\0\7\10\2\0\2\10\1\0\3\10\1\134\1\10"+
    "\1\0\2\10\2\0\2\103\3\0\1\103\12\0\11\103"+
    "\1\0\1\103\3\0\7\103\2\0\2\103\1\0\5\103"+
    "\1\0\2\103\2\0\1\103\1\104\3\0\1\103\12\0"+
    "\11\103\1\0\1\103\3\0\7\103\2\0\2\103\1\0"+
    "\5\103\1\0\2\103\2\0\2\103\3\0\1\103\1\105"+
    "\11\0\11\103\1\0\1\103\3\0\7\103\2\0\2\103"+
    "\1\0\5\103\1\0\2\103\3\0\1\106\62\0\2\10"+
    "\3\0\1\10\12\0\3\10\1\135\5\10\1\0\1\10"+
    "\3\0\7\10\2\0\2\10\1\0\5\10\1\0\2\10"+
    "\2\0\2\10\3\0\1\10\12\0\1\136\10\10\1\0"+
    "\1\10\3\0\7\10\2\0\2\10\1\0\5\10\1\0"+
    "\2\10\2\0\2\10\3\0\1\10\12\0\11\10\1\0"+
    "\1\10\3\0\7\10\2\0\1\137\1\10\1\0\1\140"+
    "\1\141\3\10\1\0\2\10\2\0\2\10\3\0\1\10"+
    "\12\0\7\10\1\142\1\10\1\0\1\10\3\0\7\10"+
    "\2\0\2\10\1\0\5\10\1\0\2\10\2\0\2\10"+
    "\3\0\1\10\12\0\6\10\1\143\1\144\1\10\1\0"+
    "\1\10\3\0\7\10\2\0\2\10\1\0\5\10\1\0"+
    "\2\10\2\0\2\10\3\0\1\10\12\0\1\145\10\10"+
    "\1\0\1\10\3\0\7\10\2\0\2\10\1\0\5\10"+
    "\1\0\2\10\2\0\2\10\3\0\1\10\12\0\1\10"+
    "\1\146\7\10\1\0\1\10\3\0\7\10\2\0\2\10"+
    "\1\0\5\10\1\0\2\10\2\0\2\10\3\0\1\10"+
    "\12\0\11\10\1\0\1\10\3\0\1\147\6\10\2\0"+
    "\2\10\1\0\5\10\1\0\2\10\2\0\2\10\3\0"+
    "\1\10\12\0\11\10\1\0\1\10\3\0\1\10\1\150"+
    "\5\10\2\0\2\10\1\0\5\10\1\0\2\10\2\0"+
    "\2\10\3\0\1\10\12\0\6\10\1\151\2\10\1\0"+
    "\1\10\3\0\7\10\2\0\2\10\1\0\5\10\1\0"+
    "\2\10\2\0\2\10\3\0\1\10\12\0\7\10\1\152"+
    "\1\10\1\0\1\10\3\0\7\10\2\0\2\10\1\0"+
    "\5\10\1\0\2\10\2\0\2\10\3\0\1\10\12\0"+
    "\4\10\1\153\4\10\1\0\1\10\3\0\7\10\2\0"+
    "\2\10\1\0\5\10\1\0\2\10\2\0\2\10\3\0"+
    "\1\10\12\0\4\10\1\154\4\10\1\0\1\10\3\0"+
    "\7\10\2\0\2\10\1\0\5\10\1\0\2\10\32\0"+
    "\1\155\56\0\1\156\64\0\1\157\107\0\1\160\36\0"+
    "\1\161\40\0\2\10\3\0\1\10\12\0\11\10\1\0"+
    "\1\10\3\0\1\162\6\10\2\0\2\10\1\0\5\10"+
    "\1\0\2\10\2\0\2\10\3\0\1\10\12\0\4\10"+
    "\1\163\4\10\1\0\1\10\3\0\7\10\2\0\2\10"+
    "\1\0\5\10\1\0\2\10\2\0\2\10\3\0\1\10"+
    "\12\0\11\10\1\0\1\10\3\0\5\10\1\164\1\10"+
    "\2\0\2\10\1\0\5\10\1\0\2\10\2\0\2\10"+
    "\3\0\1\10\12\0\11\10\1\0\1\10\3\0\7\10"+
    "\2\0\2\10\1\0\4\10\1\165\1\0\2\10\2\0"+
    "\2\10\3\0\1\10\12\0\11\10\1\0\1\10\3\0"+
    "\7\10\2\0\1\166\1\10\1\0\5\10\1\0\2\10"+
    "\2\0\2\10\3\0\1\10\12\0\11\10\1\0\1\10"+
    "\3\0\7\10\2\0\2\10\1\0\1\10\1\167\3\10"+
    "\1\0\2\10\2\0\2\10\3\0\1\10\12\0\1\170"+
    "\10\10\1\0\1\10\3\0\7\10\2\0\2\10\1\0"+
    "\5\10\1\0\2\10\2\0\2\10\3\0\1\10\12\0"+
    "\3\10\1\171\5\10\1\0\1\10\3\0\7\10\2\0"+
    "\2\10\1\0\5\10\1\0\2\10\2\0\2\10\3\0"+
    "\1\10\12\0\11\10\1\0\1\172\3\0\7\10\2\0"+
    "\2\10\1\0\5\10\1\0\2\10\2\0\2\10\3\0"+
    "\1\10\12\0\7\10\1\173\1\10\1\0\1\10\3\0"+
    "\7\10\2\0\2\10\1\0\5\10\1\0\2\10\2\0"+
    "\2\10\3\0\1\10\12\0\11\10\1\0\1\10\3\0"+
    "\7\10\2\0\1\174\1\10\1\0\5\10\1\0\2\10"+
    "\2\0\2\10\3\0\1\10\12\0\2\10\1\175\6\10"+
    "\1\0\1\10\3\0\7\10\2\0\2\10\1\0\5\10"+
    "\1\0\2\10\2\0\2\10\3\0\1\10\12\0\4\10"+
    "\1\176\4\10\1\0\1\10\3\0\7\10\2\0\2\10"+
    "\1\0\5\10\1\0\2\10\2\0\2\10\3\0\1\10"+
    "\12\0\1\177\10\10\1\0\1\10\3\0\7\10\2\0"+
    "\2\10\1\0\5\10\1\0\2\10\2\0\2\10\3\0"+
    "\1\10\12\0\6\10\1\200\2\10\1\0\1\10\3\0"+
    "\7\10\2\0\2\10\1\0\5\10\1\0\2\10\2\0"+
    "\2\10\3\0\1\10\12\0\10\10\1\201\1\0\1\10"+
    "\3\0\7\10\2\0\2\10\1\0\5\10\1\0\2\10"+
    "\2\0\2\10\3\0\1\10\12\0\11\10\1\0\1\202"+
    "\3\0\7\10\2\0\2\10\1\0\5\10\1\0\2\10"+
    "\2\0\2\10\3\0\1\10\12\0\11\10\1\0\1\10"+
    "\3\0\2\10\1\203\4\10\2\0\2\10\1\0\5\10"+
    "\1\0\2\10\26\0\1\204\75\0\1\205\63\0\1\206"+
    "\52\0\1\207\62\0\1\210\37\0\2\10\3\0\1\10"+
    "\12\0\4\10\1\211\4\10\1\0\1\10\3\0\7\10"+
    "\2\0\2\10\1\0\5\10\1\0\2\10\2\0\2\10"+
    "\3\0\1\10\12\0\11\10\1\0\1\10\3\0\7\10"+
    "\2\0\1\10\1\212\1\0\5\10\1\0\2\10\2\0"+
    "\2\10\3\0\1\10\12\0\11\10\1\0\1\10\3\0"+
    "\6\10\1\213\2\0\2\10\1\0\5\10\1\0\2\10"+
    "\2\0\1\214\1\10\3\0\1\10\12\0\11\10\1\0"+
    "\1\10\3\0\7\10\2\0\2\10\1\0\5\10\1\0"+
    "\2\10\2\0\2\10\3\0\1\10\12\0\11\10\1\0"+
    "\1\10\3\0\7\10\2\0\2\10\1\0\1\10\1\215"+
    "\3\10\1\0\2\10\2\0\2\10\3\0\1\10\12\0"+
    "\1\10\1\216\7\10\1\0\1\10\3\0\7\10\2\0"+
    "\2\10\1\0\5\10\1\0\2\10\2\0\2\10\3\0"+
    "\1\10\12\0\10\10\1\217\1\0\1\10\3\0\7\10"+
    "\2\0\2\10\1\0\5\10\1\0\2\10\2\0\2\10"+
    "\3\0\1\10\12\0\11\10\1\0\1\10\3\0\1\10"+
    "\1\220\5\10\2\0\2\10\1\0\5\10\1\0\2\10"+
    "\2\0\2\10\3\0\1\10\12\0\5\10\1\221\3\10"+
    "\1\0\1\10\3\0\7\10\2\0\2\10\1\0\5\10"+
    "\1\0\2\10\2\0\2\10\3\0\1\10\12\0\4\10"+
    "\1\222\4\10\1\0\1\10\3\0\7\10\2\0\2\10"+
    "\1\0\5\10\1\0\2\10\34\0\1\223\51\0\1\224"+
    "\13\0\1\225\63\0\1\226\65\0\1\227\54\0\1\206"+
    "\34\0\2\10\3\0\1\10\12\0\10\10\1\230\1\0"+
    "\1\10\3\0\7\10\2\0\2\10\1\0\5\10\1\0"+
    "\2\10\2\0\2\10\3\0\1\10\12\0\11\10\1\0"+
    "\1\10\3\0\1\231\6\10\2\0\2\10\1\0\5\10"+
    "\1\0\2\10\2\0\2\10\3\0\1\10\12\0\11\10"+
    "\1\0\1\10\3\0\6\10\1\232\2\0\2\10\1\0"+
    "\5\10\1\0\2\10\2\0\1\233\1\10\3\0\1\10"+
    "\12\0\11\10\1\0\1\10\3\0\7\10\2\0\2\10"+
    "\1\0\5\10\1\0\2\10\2\0\2\10\3\0\1\10"+
    "\12\0\11\10\1\0\1\10\3\0\1\234\6\10\2\0"+
    "\2\10\1\0\5\10\1\0\2\10\2\0\2\10\3\0"+
    "\1\10\12\0\1\235\10\10\1\0\1\10\3\0\7\10"+
    "\2\0\2\10\1\0\5\10\1\0\2\10\2\0\2\10"+
    "\3\0\1\10\12\0\11\10\1\0\1\10\3\0\7\10"+
    "\2\0\1\10\1\236\1\0\5\10\1\0\2\10\2\0"+
    "\2\10\3\0\1\10\12\0\11\10\1\0\1\10\3\0"+
    "\1\237\6\10\2\0\2\10\1\0\5\10\1\0\2\10"+
    "\2\0\2\10\3\0\1\10\12\0\1\10\1\240\7\10"+
    "\1\0\1\10\3\0\7\10\2\0\2\10\1\0\5\10"+
    "\1\0\2\10\36\0\1\241\53\0\1\242\57\0\1\206"+
    "\43\0\2\10\3\0\1\10\12\0\1\243\10\10\1\0"+
    "\1\10\3\0\7\10\2\0\2\10\1\0\5\10\1\0"+
    "\2\10\2\0\2\10\3\0\1\10\12\0\7\10\1\244"+
    "\1\10\1\0\1\10\3\0\7\10\2\0\2\10\1\0"+
    "\5\10\1\0\2\10\2\0\1\245\1\10\3\0\1\10"+
    "\12\0\11\10\1\0\1\10\3\0\7\10\2\0\2\10"+
    "\1\0\5\10\1\0\2\10\2\0\2\10\3\0\1\10"+
    "\12\0\4\10\1\246\4\10\1\0\1\10\3\0\7\10"+
    "\2\0\2\10\1\0\5\10\1\0\2\10\2\0\2\10"+
    "\3\0\1\10\12\0\4\10\1\247\4\10\1\0\1\10"+
    "\3\0\7\10\2\0\2\10\1\0\5\10\1\0\2\10"+
    "\2\0\2\10\3\0\1\10\12\0\1\250\10\10\1\0"+
    "\1\10\3\0\7\10\2\0\2\10\1\0\5\10\1\0"+
    "\2\10\2\0\2\10\3\0\1\10\12\0\1\251\10\10"+
    "\1\0\1\10\3\0\7\10\2\0\2\10\1\0\5\10"+
    "\1\0\2\10\2\0\2\10\3\0\1\10\12\0\7\10"+
    "\1\252\1\10\1\0\1\10\3\0\7\10\2\0\2\10"+
    "\1\0\5\10\1\0\2\10\41\0\1\253\24\0\1\254"+
    "\1\10\3\0\1\10\12\0\11\10\1\0\1\10\3\0"+
    "\7\10\2\0\2\10\1\0\5\10\1\0\2\10\2\0"+
    "\2\10\3\0\1\10\12\0\10\10\1\255\1\0\1\10"+
    "\3\0\7\10\2\0\2\10\1\0\5\10\1\0\2\10"+
    "\2\0\2\10\3\0\1\10\12\0\1\10\1\256\7\10"+
    "\1\0\1\10\3\0\7\10\2\0\2\10\1\0\5\10"+
    "\1\0\2\10\36\0\1\225\27\0\2\10\3\0\1\10"+
    "\12\0\1\257\10\10\1\0\1\10\3\0\7\10\2\0"+
    "\2\10\1\0\5\10\1\0\2\10\2\0\2\10\3\0"+
    "\1\10\12\0\2\10\1\260\6\10\1\0\1\10\3\0"+
    "\7\10\2\0\2\10\1\0\5\10\1\0\2\10\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6916];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\7\1\1\11\13\1\1\11"+
    "\2\1\1\11\1\0\2\11\1\1\1\11\1\1\4\11"+
    "\13\1\2\11\5\0\3\11\2\1\1\11\23\1\5\0"+
    "\24\1\5\0\22\1\5\0\12\1\2\0\2\11\1\0"+
    "\11\1\1\11\1\0\10\1\1\0\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[176];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public String lexema;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 186) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return ERROR;
          }
        case 55: break;
        case 2: 
          { lexema=yytext(); return ID;
          }
        case 56: break;
        case 3: 
          { lexema=yytext(); return ENTERO;
          }
        case 57: break;
        case 4: 
          { return MENOS;
          }
        case 58: break;
        case 5: 
          { /*Ignore*/
          }
        case 59: break;
        case 6: 
          { return DIVISION;
          }
        case 60: break;
        case 7: 
          { return ASIGNACION;
          }
        case 61: break;
        case 8: 
          { return MAS;
          }
        case 62: break;
        case 9: 
          { return MULTIPLICACION;
          }
        case 63: break;
        case 10: 
          { return COMA;
          }
        case 64: break;
        case 11: 
          { lexema=yytext(); return MF;
          }
        case 65: break;
        case 12: 
          { return T_DEC;
          }
        case 66: break;
        case 13: 
          { lexema=yytext(); return CADENA;
          }
        case 67: break;
        case 14: 
          { return T_CONCAT_EQUAL;
          }
        case 68: break;
        case 15: 
          { lexema=yytext(); return VARIABLE;
          }
        case 69: break;
        case 16: 
          { return T_DOLLAR_OPEN_CURLY_BRACES;
          }
        case 70: break;
        case 17: 
          { return T_DIV_EQUAL;
          }
        case 71: break;
        case 18: 
          { return IGUAL;
          }
        case 72: break;
        case 19: 
          { return T_DOUBLE_ARROW;
          }
        case 73: break;
        case 20: 
          { return DIFERENTE;
          }
        case 74: break;
        case 21: 
          { return T_AS;
          }
        case 75: break;
        case 22: 
          { return T_AND_EQUAL;
          }
        case 76: break;
        case 23: 
          { return T_BOOLEAN_AND;
          }
        case 77: break;
        case 24: 
          { return T_BOOLEAN_OR;
          }
        case 78: break;
        case 25: 
          { return T_CLOSE_TAG;
          }
        case 79: break;
        case 26: 
          { return T_CURLY_OPEN;
          }
        case 80: break;
        case 27: 
          { return T_DO;
          }
        case 81: break;
        case 28: 
          { return T_DOUBLE_COLON;
          }
        case 82: break;
        case 29: 
          { lexema=yytext(); return FLOAT;
          }
        case 83: break;
        case 30: 
          { return T_ECHO;
          }
        case 84: break;
        case 31: 
          { return T_ELSE;
          }
        case 85: break;
        case 32: 
          { return T_CASE;
          }
        case 86: break;
        case 33: 
          { return T_ENDIF;
          }
        case 87: break;
        case 34: 
          { return T_EMPTY;
          }
        case 88: break;
        case 35: 
          { return T_CONST;
          }
        case 89: break;
        case 36: 
          { return T_CATCH;
          }
        case 90: break;
        case 37: 
          { return T_CLONE;
          }
        case 91: break;
        case 38: 
          { return T_CLASS;
          }
        case 92: break;
        case 39: 
          { return T_ARRAY;
          }
        case 93: break;
        case 40: 
          { return T_BREAK;
          }
        case 94: break;
        case 41: 
          { return T_ELSEIF;
          }
        case 95: break;
        case 42: 
          { return T_ENDFOR;
          }
        case 96: break;
        case 43: 
          { return T_BOOL_CAST;
          }
        case 97: break;
        case 44: 
          { return T_DOUBLE_CAST;
          }
        case 98: break;
        case 45: 
          { return T_DIR;
          }
        case 99: break;
        case 46: 
          { return T_ARRAY_CAST;
          }
        case 100: break;
        case 47: 
          { return T_DECLARE;
          }
        case 101: break;
        case 48: 
          { return T_DEFAULT;
          }
        case 102: break;
        case 49: 
          { return T_CONTINUE;
          }
        case 103: break;
        case 50: 
          { return T_CALLABLE;
          }
        case 104: break;
        case 51: 
          { return T_ABSTRACT;
          }
        case 105: break;
        case 52: 
          { return T_CLASS_C;
          }
        case 106: break;
        case 53: 
          { return T_ENDDECLARE;
          }
        case 107: break;
        case 54: 
          { return T_ENDFOREACH;
          }
        case 108: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
